@Entry
@Component
struct TouchExample {
  @State text: string = ''
  eventType: string = ''

  build() {
    Column() {
      Button('Touch').height(50).width(200).margin(20)
        .onTouch((event: TouchEvent) => {
          if (event.type === TouchType.Down) {    this.eventType = 'Down'     }
          if (event.type === TouchType.Up) {     this.eventType = 'Up'    }
          if (event.type === TouchType.Move) {    this.eventType = 'Move'    }

          this.text = 'TouchType:' + this.eventType + '\nDistance between touch point and touch element:\nx: '
            + event.touches[0].x + '\n' + 'y: ' + event.touches[0].y + '\nComponent globalPos:('
            + event.target.area.globalPosition.x + ',' + event.target.area.globalPosition.y + ')\nwidth:'
            + event.target.area.width + '\nheight:' + event.target.area.height

        })

      Text(this.text)
    }.width('100%').padding(30)
  }
}
